### ISSUE TITLE
Lost connectivity on Reboot

### ISSUE THREAD

**Issue by DKBgit** [IQTLabs/dovesnap#755]
I am testing dovesnap on a VM (Debian GNU/Linux 11 (bullseye)). 
I followed the instructions on the readme page in the wiki and used the install script (install.sh) while having the $giturl be 'https://github.com/IQTLabs/dovesnap.git'. 
**Everything worked beautifully.**
Here is info on the docker conatiners..
```
CONTAINER ID   IMAGE                               COMMAND                  CREATED         STATUS                   PORTS
      NAMES
90a5ada21202   busybox                             "sleep 1h"               5 minutes ago   Up 5 minutes
      testcon2
4806fe876f03   busybox                             "sleep 1h"               5 minutes ago   Up 5 minutes
      testcon
561f17afe562   iqtlabs/faucetconfrpc:v0.22.38      "faucetconfrpc_serve…"   4 hours ago     Up 4 hours (healthy)     0.0.0.0:59999->59999/tcp, :::59999->59999/tcp
      dovesnap-faucetconfrpc-1
31ee48114f1a   iqtlabs/dovesnap:v1.0.10            "/dovesnap --debug -…"   4 hours ago     Up 4 hours
      dovesnap-plugin-1
41dee2328f22   c65sdn/gauge:1.0.36                 "/usr/local/bin/entr"   4 hours ago     Up 4 hours               9302-9303/tcp, 0.0.0.0:6654->6653/tcp, :::6654->6653//
tcp   dovesnap-gauge-1
d962983b7c78   iqtlabs/faucet-certstrap:v0.22.38   "sh gen_faucetconfrp"   4 hours ago     Exited (0) 4 hours ago
      dovesnap-faucet_certstrap-1
4d422c94d58d   c65sdn/faucet:1.0.36                "/usr/local/bin/entr…"   4 hours ago     Up 4 hours               0.0.0.0:6653->6653/tcp, :::6653->6653/tcp, 9302/tcp  
      dovesnap-faucet-1
31f510496cd4   iqtlabs/openvswitch:v2.17.2         "/usr/bin/supervisor"   4 hours ago     Up 4 hours (healthy)
      dovesnap-ovs-1
------------------
REPOSITORY                 TAG        IMAGE ID                                                                  CREATED        SIZE
iqtlabs/faucet-certstrap   v0.22.38   sha256:3ce6613c2133c96501742ae33a639d523765f89f9adcb07c152af885097f8c1c   8 hours ago    11.9MB
iqtlabs/faucetconfrpc      v0.22.38   sha256:4081d8478679e11160cc13bcdfa888f1974dbf0f015c034b82954220995f7461   12 hours ago   606MB
c65sdn/gauge               1.0.36     sha256:ff176320d4ecfbc76567183d3b947cae4517406849175c89e126dfa0842b9698   3 weeks ago    96.3MB
c65sdn/faucet              1.0.36     sha256:e4c1b93df948421eea55fe6e02867ac990a5baf0964bd531cac26eecb434137b   3 weeks ago    96.3MB
iqtlabs/openvswitch        v2.17.2    sha256:1264140dc89ac33e4dbf18289aba9f0cde9b99980f96604b77eaab745cde2be2   3 weeks ago    536MB
iqtlabs/dovesnap           v1.0.10    sha256:a40581e370caaf40a47e9838767e735cb9bf2b1af60023142dde4817cea444f6   4 weeks ago    194MB
busybox                    latest     sha256:62aedd01bd8520c43d06b09f7a0f67ba9720bdc04631a8242c65ea995f3ecac8   5 weeks ago    1.24MB
```
It passed the ping test to the internet..
```
david@dovetest:~$ docker exec -t testcon ping -c3 4.2.2.2
PING 4.2.2.2 (4.2.2.2): 56 data bytes
64 bytes from 4.2.2.2: seq=0 ttl=57 time=35.290 ms
64 bytes from 4.2.2.2: seq=1 ttl=57 time=34.258 ms
64 bytes from 4.2.2.2: seq=2 ttl=57 time=34.083 ms
```
And it could even ping another docker test container..
```
david@dovetest:~$ docker exec -t testcon ping -c3 testcon2
PING testcon2 (172.19.0.3): 56 data bytes
64 bytes from 172.19.0.3: seq=0 ttl=64 time=1.144 ms
64 bytes from 172.19.0.3: seq=1 ttl=64 time=0.064 ms
64 bytes from 172.19.0.3: seq=2 ttl=64 time=0.165 ms
```
But on **Reboot** is when the problems occur. When I recreate the testcon containers, they are now unable to ping the internet or each other.
```
david@dovetest:~$ docker exec -t testcon ping -c3 4.2.2.2
PING 4.2.2.2 (4.2.2.2): 56 data bytes

--- 4.2.2.2 ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
david@dovetest:~$ docker exec -t testcon ping -c3 testcon2
PING testcon2 (172.19.0.3): 56 data bytes

--- testcon2 ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
```
In order to get it to work again, I have to remove the docker network 'mynet' and then add it back again. When I add the 'testcon' docker containers, they can now ping each other and the internet.

Not sure why connectivity is not surviving on a Reboot, maybe it is an 'iptables' issue.

**Comment by anarkiwi** [comment]
Thanks very much for using dovesnap! It looks like there are two issues - the IP address for the OVS bridge is not restored after a reboot, and the accompanying NAT rule is not restored either. I will fix this. Thanks for the report.

**Comment by anarkiwi** [comment]
I found some potential issues, around OVS not maintaining interface config over reboots, and released version 1.1.1.

Please would you try this version - but beforehand, please do both a "docker system prune" and a "docker volume prune" to ensure you have all the right versions.

If you still see the problem, please do a "docker exec -ti dovesnap_ovs_1 ovs-vsctl list-br" which will get you a bridge name, and then a "docker exec -ti dovesnap_ovs_1 ovs-ofctl dump-flows <bridgename>" and send me the results? "docker logs dovesnap_plugin_1" would be helpful also.

**Comment by DKBgit** [comment]
I have tested it with the previous scenario and **everything is working very well**. 
I did notice a strange occurrence on a test that I did after a Reboot.
I created 3 docker containers :
```
docker run -d --net=mynet --rm --name=testcon busybox sleep 1h
docker run -d --net=mynet --rm --name=testcon2 busybox sleep 1h
docker run -d --net=mynet --name=maintest alpine sleep 1h       [Note: this containers isnt removed when it is shutdown.]
```
After the containers are created, 'faucet.yaml' shows : 
```
dps:
  mynet:
    description: OVS Bridge odsbr33116
    dp_id: 1
    egress_pipeline: false
    hardware: Open vSwitch
    interfaces:
      1:
        acls_in: []
        description: /testcon 0f88e
        native_vlan: 100
      2:
        acls_in: []
        description: /testcon2 9c65b
        native_vlan: 100
      3:
        acls_in: []
        description: /maintest f9d6e
        native_vlan: 100
      4294967294:
        acls_in: []
        description: OVS Port default gateway
        native_vlan: 100
```
After a Reboot and the (re)start of the docker container 'maintest' only.
`docker start maintest`
'faucet.yaml' now shows : 
```
dps:
  mynet:
    description: OVS Bridge odsbr33116
    dp_id: 1
    egress_pipeline: false
    hardware: Open vSwitch
    interfaces:
      1:
        acls_in: []
        description: /maintest f9d6e
        native_vlan: 100
      2:
        acls_in: []
        description: /testcon2 9c65b
        native_vlan: 100
      3:
        acls_in: []
        description: /maintest f9d6e
        native_vlan: 100
      4294967294:
        acls_in: []
        description: OVS Port default gateway
        native_vlan: 100
```
I noticed that 'maintest' now shows at port 1 & 3 in 'faucet.yaml'.
Even though it shows like this, the container is still able to ping external IPs. And when I add the 'testcon' containers, they overwrite positions 2 & 3 in 'faucet.yaml' but they still work.

I wanted to share my test results.
